Add Netlify Logo #51
FCCColumbus/cbus-web pull request #56
Opened 2023-08-02 17:05 UTC by mmcbride2929

# TL/DR
This PR updates the footer component by adding the netlify logo.

# Overview of Change

`Footer.jsx`
- Add <a> & <img/> tags with netlify link & logo
- Add className to <a> tag

`index.css`
- Style <a> & <img/> tags 

![netlify-logo](https://github.com/FCCColumbus/cbus-web/assets/77947488/334b7f25-c97b-421c-b34b-10f03b699d06)

2023-08-02 17:26 UTC, readysetagile requested changes
the footer test is failing.  please fix

```Snapshot Summary
 › 2 snapshots failed from 2 test suites. Inspect your code changes or press `u` to update them.

Test Suites: 2 failed, 6 passed, 8 total
Tests:       2 failed, 12 passed, 14 total
Snapshots:   2 failed, 6 passed, 8 total
Time:        4.47 s
Ran all test suites.
```

2023-08-02 18:54 UTC, jduffey commented on src/index.css
> +footer .image-wrapper {
<img width="191" alt="Screenshot 2023-08-02 at 2 54 05 PM" src="https://github.com/FCCColumbus/cbus-web/assets/22714448/150c4fd4-bc50-43fe-aa00-164f221d6129">

Nit: fix formatting, remove extra whitespace.

2023-08-02 18:58 UTC, jduffey commented on src/index.css
> +footer .image-wrapper {
<img width="401" alt="Screenshot 2023-08-02 at 2 56 17 PM" src="https://github.com/FCCColumbus/cbus-web/assets/22714448/914a01d7-ba31-4ba6-9c29-ad2a980af948">

fwiw I only first noticed this by doing a local diff of your branch against the `upstream/dev` branch (after making sure to pull in order to be up-to-date). You can see the red in the console, indicating there's extra whitespace. (Not all terminals will be configured to show this necessarily; it's probably a default setting that comes with macOS Xcode tools or some other terminal settings I have applied.)

2023-08-02 18:59 UTC, jduffey commented
Overall, looks good. I'll wait till the failing test is resolved before approving.

2023-08-03 12:59 UTC, jduffey approved these changes
The minor formatting issue and failing test have been addressed. Everything looks good on `51453b4`. Approved. :shipit:

2023-08-03 14:36 UTC, readysetagile approved these changes
+1 passed

2023-08-03 14:36 UTC, merged