update-contributors-section
FCCColumbus/cbus-web pull request #64
Opened 2023-08-30 18:18 UTC by mmcbride2929

# TL/DR
This PR updates members section, and links to the contributors graph page.`

# Overview of Change

`Members.jsx`
- updates members array with new imgUrl links
- updates members array with full list of contributors
- changed contributors member's name from an `<h4>` to a `<h5>` to maintain consistent spacing with
  admins
- wrapped contributors div with an a tag, to link to contributors graph

`index.css`
- increase member avatar size to 125px from 100px

![Untitled](https://github.com/FCCColumbus/cbus-web/assets/77947488/931b9674-6ae0-4811-b6e6-f99165f87de9)

2023-08-30 18:21 UTC, mmcbride2929 commented
A little over halfway completing this ticket I realized the instructions were to add the contributor's photos via a single photo that was linked in the issue. I went back and forth if I should change it but decided to

2023-09-01 00:34 UTC, readysetagile commented
@mmcbride2929 now that the lint issues are fixed you can re-run your checks in this PR by pushing an empty commit:
```
git checkout <this branch>
git commit -m "retrigger checks" --allow-empty
git push ...
```

2023-09-01 00:46 UTC, readysetagile requested changes
actually - nix my last comment

the contributors section pictures should reflect what is in the Contributors section of the repo.  So you should be pictured there and you are not.  See the requirement...

```
GIVEN I am a FreeCodeCamp user
WHEN I view the "Meet the Contributors" section
THEN I will see the image of contributors generated by the [contrib.rocks](https://contrib.rocks/image?repo=FCCColumbus/cbus-web) website
```

2023-09-02 17:23 UTC, jduffey commented
`npm test` is failing for me at `704bc83`. Need to update snapshot for the Members component.

2023-09-02 19:57 UTC, Toilaf commented on src/components/Members.jsx
> +              <h5>{member.name}</h5>
Is there a way to change the spacing on these without changing the semantic structure? https://www.a11yproject.com/posts/how-to-accessible-heading-structure/#best-practices-summarized

2023-09-06 01:44 UTC, readysetagile requested changes
We need to remove the `members` structure and all the supporting code.  The names below each person's icon is not part of the requirement.  The reason for this is because the image at contrib.rocks is dynamically created every time a new member has code merged into our repo.  We do not want to change the contributors section every time a new member merges code.  Clicking on the contributors image will give our members an "identity" by navigating the user to the gihub activity graph.  

The snapshot test for the component will also need to be changed, but it should be much much simpler...

2023-09-13 21:27 UTC, jduffey commented on src/components/Members.jsx
> +            <img className='members-avatar' src='https://contrib.rocks/image?repo=FCCColumbus/cbus-web' alt='beautiful headshots of our members' />
Suggest renaming this style class to `contributors-avatar`, since it applies only to Contributors and not Admins, who are also "Members".

2023-09-13 21:29 UTC, jduffey commented on src/components/Members.jsx
>        <div className="members">
Suggest changing this to "admins" (or "administrators" if you want) for readability (i.e. in order to more clearly indicate that code-wise, Admins and Contributors are both equally Members). If you do decide to implement this change, make sure to update all relevant names in the CSS.

2023-09-20 12:47 UTC, jduffey approved these changes
Looks good, nice work! :shipit:

2024-02-22 02:07 UTC, StevenH34 commented
What is the status of this PR?

2024-02-24 19:18 UTC, readysetagile commented
No merge was performed before #75 was merged.  @jsolly identified the weirdness of the commits and I misdiagnosed it during the hackathon.  looked at both PRs, and I am thinking that when I approve #75 that the changes for this PR will still be OK.  I'll re-run the checks again for completeness.

2024-02-24 19:26 UTC, readysetagile approved these changes

2024-02-24 19:27 UTC, merged