React cal poc kl
FCCColumbus/cbus-web pull request #85
Opened 2024-03-09 22:49 UTC by KVinyl

Changelog from #79 
Moved calendar and event cards to one row.
Allow multiple event cards to be displayed.
Scroll bar is shown when multiple event cards are displayed.
No event cards are shown when selected date has no events.
Text color of day number during the weekend in calendar is white when selected or has event instead of black.

--
Event card text needs formatting.
Does not look good on mobile.
Lots of module warnings during webpack compilation.

2024-03-09 22:54 UTC, KVinyl commented
@readysetagile

2024-03-11 15:43 UTC, readysetagile commented
@KVinyl please resolve the merge conflicts and the linting errors

2024-03-12 18:03 UTC, KVinyl commented
@readysetagile Merge conflicts and linting errors have been resolved. Did some further refactoring. Of course, more needs to be done, just looking for feedback for I have so far.

2024-03-12 20:55 UTC, readysetagile commented
@KVinyl a test is failing.  Make sure you run `npm run build && npm run lint && npm run test` before pushing

2024-03-14 20:41 UTC, KVinyl commented
@readysetagile Updated the snapshots to pass testing.

2024-03-20 18:21 UTC, KVinyl commented
@readysetagile Further optimization, refactor, minor bug fixes

2024-03-20 20:59 UTC, readysetagile requested changes
It looks like it works great, so nice work there!  

I think that we might want to follow good design patterns here also -- like a MVC.  So let's move the code that is currently in `Events.jsx` into a controller structure, that is, `eventsController.js`  The model is already taken care of in the calendar control.  That way `Events.jsx` becomes the "view", and just handles user events and initialization.  you can ask GPT this question to know what I mean:

> can this react.js code for Events.jsx be refactored so that it follows a view-controller design, that is, the Events.jsx serves as a view to just handle user events and initialization, and the controller does the stuff that happens when an event is fired? [include the code for Events.jsx] 

Seeing this will also likely bring up more refactoring, like being able to configure the link for the calendar through a file and possibly make it data driven also -- along with other maintainability concerns, so let's start with the controller.

2024-03-26 22:59 UTC, KVinyl commented
@readysetagile Created two custom hooks. useEvents is responsible for fetching events. useCalendar takes in events as an input and returns the variables/functions used by the Calendar/Events section. 

Fixed unwanted multiple events CSS behavior in Chrome.

2024-04-01 14:13 UTC, readysetagile commented on src/hooks/useEvents.js
> +        'https://docs.google.com/document/d/1OcnWWt1qHaJWE-8v_FPtNO8DKviRQ7DMaqylupuvPXE/export?format=txt'
We will create another backlog item to make this value configurable.  It's outside the scope of this backlog item.

2024-04-01 14:19 UTC, readysetagile approved these changes
Well done, @KVinyl !  This captures the essence of a good design.

2024-04-01 14:19 UTC, merged